package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author 
 */
public class Escalera extends javax.swing.JDialog {

    /**
     * Creates new form Habitacion1
     */
    public Escalera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Escalera");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonHabitacion1 = new javax.swing.JLabel();
        botonHabitacion1.setBounds(80, 80, 170, 40);
        
        apagar = new javax.swing.JLabel();
        apagar.setBounds(70, 70, 110, 60);
        
        barraProgreso = new javax.swing.JProgressBar();
        barraProgreso.setBounds(60, 200, 220, 20);
        
        grados = new javax.swing.JLabel();
        grados.setBounds(170, 260, 60, 60);
        
        panelGrados = new javax.swing.JTextField();
        panelGrados.setBounds(110, 260, 60, 60);
        
        panelPrincipal = new javax.swing.JLabel();
        panelPrincipal.setBounds(0, 0, -1, 340);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        botonHabitacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apagado.png"))); // NOI18N
        botonHabitacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonHabitacion1MouseClicked(evt);
            }
        });
        jPanel1.add(botonHabitacion1);

        apagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apagarMouseClicked(evt);
            }
        });
        jPanel1.add(apagar);

        barraProgreso.setString("0");
        barraProgreso.setStringPainted(true);
        jPanel1.add(barraProgreso);

        grados.setBackground(new java.awt.Color(112, 112, 112));
        grados.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        grados.setForeground(new java.awt.Color(112, 112, 112));
        grados.setText("Cº");
        jPanel1.add(grados);

        panelGrados.setBackground(new java.awt.Color(239, 240, 240));
        panelGrados.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        panelGrados.setForeground(new java.awt.Color(112, 112, 112));
        panelGrados.setText("20");
        panelGrados.setBorder(null);
        jPanel1.add(panelGrados);

        panelPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Escalera.png"))); // NOI18N
        jPanel1.add(panelPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonHabitacion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHabitacion1MouseClicked
        // TODO add your handling code here:
        String path = "/img/encendido.png";
        URL url = this.getClass().getResource(path);
        ImageIcon icon = new ImageIcon(url);
        botonHabitacion1.setIcon(icon);
    }//GEN-LAST:event_botonHabitacion1MouseClicked

    private void apagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apagarMouseClicked
        // TODO add your handling code here:
        String path = "/img/apagado.png";
        URL url = this.getClass().getResource(path);
        ImageIcon icon = new ImageIcon(url);
        botonHabitacion1.setIcon(icon);
    }//GEN-LAST:event_apagarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escalera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escalera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escalera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escalera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Escalera dialog = new Escalera(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apagar;
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JLabel botonHabitacion1;
    private javax.swing.JLabel grados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField panelGrados;
    private javax.swing.JLabel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
