package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setTitle("Menu Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setLayout(null);
        
        Apagar = new javax.swing.JLabel();
        Apagar.setBounds(300, 260, 160, 120);
        
        habitacion1 = new javax.swing.JLabel();
        habitacion1.setBounds(70, 110, 160, 120);
        
        habitacion2 = new javax.swing.JLabel();
        habitacion2.setBounds(70, 270, 160, 120);
        
        escaleras = new javax.swing.JLabel();
        escaleras.setBounds(300, 110, 160, 120);
        
        panelPrincipal = new javax.swing.JLabel();
        panelPrincipal.setBounds(10, 10, 530, -1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


        Apagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApagarMouseClicked(evt);
            }
        });
        jPanel1.add(Apagar);

        habitacion1.setForeground(new java.awt.Color(240, 240, 240));
        habitacion1.setText(".");
        habitacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habitacion1MouseClicked(evt);
            }
        });
        jPanel1.add(habitacion1);

        habitacion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habitacion2MouseClicked(evt);
            }
        });
        jPanel1.add(habitacion2);

        escaleras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escalerasMouseClicked(evt);
            }
        });
        jPanel1.add(escaleras);

        panelPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuPrincipal.png"))); // NOI18N
        jPanel1.add(panelPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApagarMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hasta pronto,vuelva pronto.");

        System.exit(0);
    }//GEN-LAST:event_ApagarMouseClicked

    private void habitacion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habitacion2MouseClicked
        // TODO add your handling code here:
        Habitacion2 hab2 = new Habitacion2(this, true);
        hab2.setVisible(true);
        hab2.setTitle("Habitacion 2");
        hab2.setLocationRelativeTo(null);
    }//GEN-LAST:event_habitacion2MouseClicked

    private void escalerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escalerasMouseClicked
        // TODO add your handling code here:
        Escalera escalera = new Escalera(this, true);
        escalera.setVisible(true);
        escalera.setTitle("Escaleras");
        escalera.setLocationRelativeTo(null);
    }//GEN-LAST:event_escalerasMouseClicked

    private void habitacion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habitacion1MouseClicked
        // TODO add your handling code here:
        Habitacion1 hab1 = new Habitacion1(this, true);
        hab1.setVisible(true);
        hab1.setTitle("Habitacion 1");
        hab1.setLocationRelativeTo(null);

    }//GEN-LAST:event_habitacion1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apagar;
    private javax.swing.JLabel escaleras;
    private javax.swing.JLabel habitacion1;
    private javax.swing.JLabel habitacion2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
